# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
  - "3.8-dev"
  - "pypy3.5"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install .
  - pip install -r requirements_dev.txt
script: pytest


# command to run tests, e.g. python setup.py test
# script: tox -e ${TOXENV}

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jmclarty
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: jnmclarty/pyenvdiff
    condition: $TOXENV == py27
